### ISSUE TITLE
Rails 3

### ISSUE THREAD

**Issue by andypearson** [lancejpollard/cockpit#1]
I've been eyeing up this project for a while...

Just about to try it, and realised it isn't actually a gem!

Are there plans to make it Rails 3 compatible, and has it been used in a production Rails app?

More than happy to provide pull requests!

**Comment by andypearson** [comment]
So, I found a mysterious gem...
http://rubygems.org/gems/cockpit

Digging deeper.

**Comment by lancejpollard** [comment]
That's the same gem :).  I'm using it right now in developing a production app.  I'm getting a prototype release up next week, and I need that gem for it, but there's a bit of optimizations to do b/c I'm using it with ActiveRecord in this project.  Used it with mongodb in another.  Using it for a profile object associated with users and groups, for global site settings, and for user-specific preferences.  Stay tuned!

**Comment by andypearson** [comment]
Great, I'm going to spend some time with Cockpit over the weekend, just got to throw together a single settings page for a CMS. I'm using Active Record for that one.

I'll let you know how it goes and I'm looking forward to the release!

Issue closed for now!
