### ISSUE TITLE
Where is the db schema?

### ISSUE THREAD

**Issue by acgray** [lancejpollard/cockpit#4]
Have just tried installing this and when using :active_record it uses a db table 'settings'. But I can't find a migration for it anywhere. Is there something thick I'm doing wrong?

**Comment by lancejpollard** [comment]
Hey,

There's no migration for it, should have included it in the docs!

Just add this in a migration:

``` ruby
create_table :settings, :force => true do |t|
  t.string :key
  t.string :value
  t.string :context
  t.string :configurable_type
  t.integer :configurable_id
end
```
